# Generated by Django 5.2.5 on 2025-08-14 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('cpf', models.CharField(max_length=11, verbose_name='Número do CPF')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('titulo', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('public_data', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aula2.reporter')),
            ],
        ),
    ]
