# Generated by Django 5.2.5 on 2025-08-13 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('data_nasc', models.DateField(verbose_name='Nascimento')),
                ('cpf', models.CharField(max_length=11, verbose_name='Número do CPF')),
            ],
        ),
        migrations.CreateModel(
            name='Passaporte',
            fields=[
                ('numero', models.CharField(max_length=100, verbose_name='Número')),
                ('data_criacao', models.DateField(verbose_name='Data Criação')),
                ('data_exp', models.DateField(verbose_name='Data Expiração')),
                ('dono', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aula.pessoa')),
            ],
        ),
    ]
