# Generated by Django 5.2.5 on 2025-08-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('chassi', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=7)),
            ],
        ),
    ]
